language: minimal

services:
  - docker

before_install:
  - docker --version

script:
  - docker build --build-arg VERSION=$(cat VERSION) -t ressetkk/gitspy-backend:$(cat VERSION) -t ressetkk/gitspy-backend:latest ./backend/

before_deploy:
  - docker login --username $user --password $token
  - docker push ressetkk/gitspy-backend
