language: minimal
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - GCLOUD_HOME="$HOME/google-cloud-sdk"
before_install:
- openssl aes-256-cbc -K $encrypted_dd148705a60e_key -iv $encrypted_dd148705a60e_iv
  -in secret-gcloud.json.enc -out secret-gcloud.json -d
- docker --version
- export VERSION=$(cat VERSION)
install:
- curl https://sdk.cloud.google.com | bash > /dev/null
- gcloud -v
- ". $GCLOUD_HOME/path.bash.inc"
- gcloud config set disable_usage_reporting true
- gcloud --quiet components update kubectl
before_script:
- gcloud auth activate-service-account --key-file secret-gcloud.json
- yes | gcloud auth configure-docker
script:
- docker build --build-arg VERSION=$VERSION -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend:$VERSION
  -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend:latest ./backend/
- docker build --build-arg VERSION=$VERSION -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend:$VERSION
  -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend:latest ./frontend/
after_success:
- docker push $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend
- docker push $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend
- gcloud container clusters get-credentials $GKE_NAME --zone=europe-west1-b --project
  $GCLOUD_PROJECT_ID
- kubectl apply -f backend-deployment.yml
- kubectl applly -f frontend-deployment.yml
