language: minimal
services:
- docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: oGWS+Va79eym45Zi595+wgpoAOwJXmz23rEFYbRfgWf2NtVmj2mL2r7WPVXa78Hxs+jFiae4+AIy/JPFQc/Yc8D3sf9ZQ/gQd0dWovao+yvRDucgxRsm9Z+AC2rqU+oMZcYd+dCBaPrUc1oXMj6ohWVwe6rKmAttFzb1oRbvuVJBdVtOmOSxAdXkJGuBC4H9gmIDlYOyRxJqDJ4beTVCbX2/L8iKkkOBv1Ika/s4Atf8I8Hvkn9cOQHu5ffeDeqas33uHLbUr0RW2sfjhMklT9qF+8vk2ZseVYINSTWTWGSxpLREnsG7D2hZW7guIzQr74C/rWY6RRULY5cf4dNStRLxmc/7hKNJxQG5RMb1m3ihKeta2ZqXK6Jxv/7clJWtG0YnnCxrlfr1MY3yIcSN5TfClw3jrFfvjr0AaG1nexmC1tRFg7ga3fmXTTZ3AnrbJF8i3sOMidy+AjjPuJHU83kxn3mPgy7L+T3Cez2SKNeL1aaQQ09HWn58bKfJGs4u8IfZWkMKZ4tLTW1pQSEEbcHOXu5saFzGfXz/oCD3Q8hr54ybo4RStUPPDgwwbXTxYCunjNfvP1jLjBP3VNlqqxhENt1Ojyq/NS7NZfPqzpRbNPg7hCt2tPBpyGfjCUuNUApdUXCzN0rCPidRPeunldFS42t8ZOht8gHQZ2NszNQ=
  - GCLOUD_HOME="$HOME/google-cloud-sdk"
  - GCR_URL=eu.gcr.io
  - secure: JVDdf8ycj71iwhCdJ9Q86WEyjEHZFRhYS2RwolIPClgFM6oapwJNst0a4eIiFXkdBDX3euh9m+BYSUktkmjbsLnLwO37Zx8bwn9YSMLcWfllOUABUE3dTxBkY1GtwQoJpzg6yGNPGI/nD7dPog+V8sWVQmyq2oG/34IJTB8XxXCJN13/KWI0XyA+L3YXgMYMTLIcnBsjZiEp/nPDG/0dLJbptoU/PuK4i27Pwwn0oiLmu4LRb72H2o9nD/tRiyqin9yNT3aBsR0PvmyadHdiHzPUd/n52Dt2UwpahuaXH49ZejapX4k2Kn80UNKeOpXr8qLWvg3FZQ9pMwlFgEkL9h9tjjH1ufMDsRFtFqGEZdeM35KfV1xBPQdQL9BcjDxmcZf5ByQJQQRg0noYoYQTT5EAtvsjP3vS8nAUYY+gS1zo2K5uMfn08Zv2UW2TSYqv4/1vwpDv3x+afgYwSLSANILyv/yenMgN44W+EmqtLJcBCwWTfXKydC5Gh1Q5HCXlnl8zcZwuX298sRVVQO6TIw4YaJ209i5OVjvRt95Cl6KlfDZpCIPjwyrdcNgAGk1jZRMBAWOufcXQfnbuBcoO6nAnvTUJs5eHuZXI1LDoCow0tvSqJ9jkNp+DuCw2YdhPrAfE8qznQxpiJrPlNfjqER9zWCDsxQmm9nH+zi6YBTU=
before_install:
- openssl aes-256-cbc -K $encrypted_dd148705a60e_key -iv $encrypted_dd148705a60e_iv
  -in secret-gcloud.json.enc -out ./secret-gcloud.json -d
- docker --version
- export VERSION=$(cat VERSION)
install:
- curl https://sdk.cloud.google.com | bash > /dev/null
- gcloud -v
- ". $GCLOUD_HOME/path.bash.inc"
- gcloud config set disable_usage_reporting true
- gcloud --quiet components update kubectl
before_script:
- gcloud auth activate-service-account --key-file secret-gcloud.json
- yes | gcloud auth configure-docker
script:
- docker build --build-arg VERSION=$VERSION -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend:$VERSION
  -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend:latest ./backend/
- docker build --build-arg VERSION=$VERSION -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend:$VERSION
  -t $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend:latest ./frontend/
after_success:
- docker push $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-backend
- docker push $GCR_URL/$GCLOUD_PROJECT_ID/gitspy-frontend
- gcloud container clusters get-credentials $GKE_NAME --zone=europe-west1-b --project
  $GCLOUD_PROJECT_ID
- kubectl apply -f backend-deployment.yml
- kubectl applly -f frontend-deployment.yml
