language: minimal

services:
  - docker

before_install:
  - docker --version
  - export VERSION=$(cat VERSION)

script:
  - docker build --build-arg VERSION=$VERSION -t ressetkk/gitspy-backend:$VERSION -t ressetkk/gitspy-backend:latest ./backend/
  - docker build --build-arg VERSION=$VERSION -t ressetkk/gitspy-frontend:$VERSION -t ressetkk/gitspy-frontend:latest ./frontend/

after_script:
  - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
  - docker push ressetkk/gitspy-backend
  - docker push ressetkk/gitspy-frontend
