apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitspy-backend-deployment
  labels:
    app: gitspy-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitspy-backend
  template:
    metadata:
      labels:
        app: gitspy-backend
    spec:
      containers:
        - name: backend
          image: eu.gcr.io/prywatny-260522/gitspy-backend:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gitspy-backend-service
  labels:
    app: gitspy-backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitspy-backend
  type: NodePort