apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitspy-frontend-deployment
  labels:
    app: gitspy-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitspy-frontend
  template:
    metadata:
      labels:
        app: gitspy-frontend
    spec:
      containers:
        - name: frontend
          image: eu.gcr.io/prywatny-260522/gitspy-frontend:latest
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gitspy-frontend-service
  labels:
    app: gitspy-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gitspy-frontend
  type: NodePort